/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazUsuario;

/**
 *
 * @author JHumaran
 */
public class AgregarCliente extends javax.swing.JFrame {

    /**
     * Creates new form AgregarCliente
     */
    public AgregarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNombres = new javax.swing.JLabel();
        botonAgregarImagen = new javax.swing.JButton();
        labelApellidoPaterno = new javax.swing.JLabel();
        labelApellidoMaterno = new javax.swing.JLabel();
        labelGenero = new javax.swing.JLabel();
        labelClave = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelFechaAlta = new javax.swing.JLabel();
        campoTextoClave = new javax.swing.JTextField();
        campoTextoFechaAlta = new javax.swing.JTextField();
        labelFechaNacimiento = new javax.swing.JLabel();
        campoTextoFechaNacimiento = new javax.swing.JTextField();
        comboGenero = new javax.swing.JComboBox();
        campoTextoApellidoMaterno = new javax.swing.JTextField();
        campoTextoApellidoPaterno = new javax.swing.JTextField();
        campoTextoNombres = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        labelDomicilio = new javax.swing.JLabel();
        labelCelular = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        campoTextoDomicilio = new javax.swing.JTextField();
        campoTextoCelular = new javax.swing.JTextField();
        campoTextoEmail = new javax.swing.JTextField();
        botonNuevoCliente = new javax.swing.JButton();
        botonGuardarCliente = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Cliente");
        setResizable(false);

        labelNombres.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelNombres.setForeground(new java.awt.Color(102, 102, 102));
        labelNombres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombres.setText("Nombre(s):");

        botonAgregarImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazUsuario/img/AgregarImagen (1).png"))); // NOI18N
        botonAgregarImagen.setToolTipText("Agrega una imagen del cliente");

        labelApellidoPaterno.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelApellidoPaterno.setForeground(new java.awt.Color(102, 102, 102));
        labelApellidoPaterno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelApellidoPaterno.setText("Apellido Paterno:");

        labelApellidoMaterno.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelApellidoMaterno.setForeground(new java.awt.Color(102, 102, 102));
        labelApellidoMaterno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelApellidoMaterno.setText("Apellido Materno:");

        labelGenero.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelGenero.setForeground(new java.awt.Color(102, 102, 102));
        labelGenero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGenero.setText("Género:");

        labelClave.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelClave.setForeground(new java.awt.Color(102, 102, 102));
        labelClave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClave.setText("Clave:");

        labelFechaAlta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelFechaAlta.setForeground(new java.awt.Color(102, 102, 102));
        labelFechaAlta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFechaAlta.setText("Fecha de Alta:");

        campoTextoClave.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoTextoClave.setForeground(new java.awt.Color(102, 102, 102));
        campoTextoClave.setText("jTextField2");
        campoTextoClave.setEnabled(false);

        campoTextoFechaAlta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoTextoFechaAlta.setForeground(new java.awt.Color(102, 102, 102));
        campoTextoFechaAlta.setText("jTextField2");
        campoTextoFechaAlta.setEnabled(false);

        labelFechaNacimiento.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelFechaNacimiento.setForeground(new java.awt.Color(102, 102, 102));
        labelFechaNacimiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFechaNacimiento.setText("Fecha de Nacimiento:");

        campoTextoFechaNacimiento.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoTextoFechaNacimiento.setForeground(new java.awt.Color(102, 102, 102));

        comboGenero.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        comboGenero.setForeground(new java.awt.Color(102, 102, 102));
        comboGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hombre", "Mujer" }));

        campoTextoApellidoMaterno.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoTextoApellidoMaterno.setForeground(new java.awt.Color(102, 102, 102));

        campoTextoApellidoPaterno.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoTextoApellidoPaterno.setForeground(new java.awt.Color(102, 102, 102));

        campoTextoNombres.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoTextoNombres.setForeground(new java.awt.Color(102, 102, 102));

        labelDomicilio.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelDomicilio.setForeground(new java.awt.Color(102, 102, 102));
        labelDomicilio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDomicilio.setText("Domicilio:");

        labelCelular.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelCelular.setForeground(new java.awt.Color(102, 102, 102));
        labelCelular.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCelular.setText("Celular:");

        labelEmail.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(102, 102, 102));
        labelEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEmail.setText("Email:");

        campoTextoDomicilio.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoTextoDomicilio.setForeground(new java.awt.Color(102, 102, 102));

        campoTextoCelular.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoTextoCelular.setForeground(new java.awt.Color(102, 102, 102));

        campoTextoEmail.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoTextoEmail.setForeground(new java.awt.Color(102, 102, 102));

        botonNuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazUsuario/img/AgregarCliente.png"))); // NOI18N
        botonNuevoCliente.setPreferredSize(new java.awt.Dimension(73, 73));

        botonGuardarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazUsuario/img/Guardar.png"))); // NOI18N
        botonGuardarCliente.setPreferredSize(new java.awt.Dimension(73, 73));
        botonGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarClienteActionPerformed(evt);
            }
        });

        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazUsuario/img/Salir (1).png"))); // NOI18N
        botonSalir.setPreferredSize(new java.awt.Dimension(73, 73));
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(botonAgregarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelClave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoTextoClave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelFechaAlta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoTextoFechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelGenero)
                                    .addComponent(labelApellidoMaterno)
                                    .addComponent(labelApellidoPaterno)
                                    .addComponent(labelNombres)
                                    .addComponent(labelFechaNacimiento))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoTextoFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoTextoNombres)
                                    .addComponent(campoTextoApellidoPaterno)
                                    .addComponent(campoTextoApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelCelular)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(campoTextoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelEmail)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoTextoEmail))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelDomicilio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoTextoDomicilio)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonGuardarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelClave)
                            .addComponent(campoTextoClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelFechaAlta)
                            .addComponent(campoTextoFechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNombres)
                            .addComponent(campoTextoNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelApellidoPaterno)
                            .addComponent(campoTextoApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelApellidoMaterno)
                            .addComponent(campoTextoApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoTextoFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botonAgregarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDomicilio)
                            .addComponent(campoTextoDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCelular)
                            .addComponent(campoTextoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEmail)
                            .addComponent(campoTextoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botonNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonGuardarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarClienteActionPerformed
        dispose();
    }//GEN-LAST:event_botonGuardarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarImagen;
    private javax.swing.JButton botonGuardarCliente;
    private javax.swing.JButton botonNuevoCliente;
    private javax.swing.JButton botonSalir;
    private javax.swing.JTextField campoTextoApellidoMaterno;
    private javax.swing.JTextField campoTextoApellidoPaterno;
    private javax.swing.JTextField campoTextoCelular;
    private javax.swing.JTextField campoTextoClave;
    private javax.swing.JTextField campoTextoDomicilio;
    private javax.swing.JTextField campoTextoEmail;
    private javax.swing.JTextField campoTextoFechaAlta;
    private javax.swing.JTextField campoTextoFechaNacimiento;
    private javax.swing.JTextField campoTextoNombres;
    private javax.swing.JComboBox comboGenero;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelApellidoMaterno;
    private javax.swing.JLabel labelApellidoPaterno;
    private javax.swing.JLabel labelCelular;
    private javax.swing.JLabel labelClave;
    private javax.swing.JLabel labelDomicilio;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelFechaAlta;
    private javax.swing.JLabel labelFechaNacimiento;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JLabel labelNombres;
    // End of variables declaration//GEN-END:variables
}
