/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazUsuario;

/**
 *
 * @author JHumaran
 */
public class HistorialCliente extends javax.swing.JFrame {

    /**
     * Creates new form HistorialCliente
     */
    public HistorialCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelClientes = new javax.swing.JPanel();
        botonAgregarImagen = new javax.swing.JButton();
        labelClave = new javax.swing.JLabel();
        campoTextoClave = new javax.swing.JTextField();
        labelFechaAlta = new javax.swing.JLabel();
        campoTextoFechaAlta = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        labelNombres = new javax.swing.JLabel();
        campoTextoNombres = new javax.swing.JTextField();
        labelApellidoPaterno = new javax.swing.JLabel();
        campoTextoApellidoPaterno = new javax.swing.JTextField();
        labelApellidoMaterno = new javax.swing.JLabel();
        campoTextoApellidoMaterno = new javax.swing.JTextField();
        labelGenero = new javax.swing.JLabel();
        comboGenero = new javax.swing.JComboBox();
        labelFechaNacimiento = new javax.swing.JLabel();
        campoTextoFechaNacimiento = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        campoTextoDomicilio = new javax.swing.JTextField();
        labelDomicilio = new javax.swing.JLabel();
        labelCelular = new javax.swing.JLabel();
        campoTextoCelular = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        campoTextoEmail = new javax.swing.JTextField();
        botonEditarCliente = new javax.swing.JButton();
        botonGuardarCliente = new javax.swing.JButton();
        botonEliminarCliente = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        panelOdontograma = new javax.swing.JPanel();
        panelDientes = new javax.swing.JPanel();
        labelPlacaSuperior = new javax.swing.JLabel();
        diente18 = new javax.swing.JButton();
        diente17 = new javax.swing.JButton();
        diente16 = new javax.swing.JButton();
        diente15 = new javax.swing.JButton();
        diente14 = new javax.swing.JButton();
        diente13 = new javax.swing.JButton();
        diente12 = new javax.swing.JButton();
        diente11 = new javax.swing.JButton();
        diente21 = new javax.swing.JButton();
        diente22 = new javax.swing.JButton();
        diente23 = new javax.swing.JButton();
        diente24 = new javax.swing.JButton();
        diente25 = new javax.swing.JButton();
        diente26 = new javax.swing.JButton();
        diente27 = new javax.swing.JButton();
        diente28 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        diente38 = new javax.swing.JButton();
        diente37 = new javax.swing.JButton();
        diente36 = new javax.swing.JButton();
        diente35 = new javax.swing.JButton();
        diente34 = new javax.swing.JButton();
        diente33 = new javax.swing.JButton();
        diente32 = new javax.swing.JButton();
        diente31 = new javax.swing.JButton();
        diente41 = new javax.swing.JButton();
        diente42 = new javax.swing.JButton();
        diente43 = new javax.swing.JButton();
        diente44 = new javax.swing.JButton();
        diente45 = new javax.swing.JButton();
        diente46 = new javax.swing.JButton();
        diente47 = new javax.swing.JButton();
        diente48 = new javax.swing.JButton();
        labelPlacaInferior = new javax.swing.JLabel();
        panelConsultas = new javax.swing.JPanel();
        tablaConsultas = new javax.swing.JScrollPane();
        tablaConsultas1 = new javax.swing.JTable();
        campoTextoUltimaConsulta = new javax.swing.JTextField();
        labelUltimaConsulta = new javax.swing.JLabel();
        botonEliminarConsulta = new javax.swing.JButton();
        campoTextoDeuda = new javax.swing.JTextField();
        labelDeuda = new javax.swing.JLabel();
        botonInformacionConsulta = new javax.swing.JButton();
        botonAgregarConsulta = new javax.swing.JButton();
        botonAgregarPago = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cliente");
        setResizable(false);

        panelClientes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 10), new java.awt.Color(102, 102, 102))); // NOI18N

        botonAgregarImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazUsuario/img/AgregarImagen (1).png"))); // NOI18N
        botonAgregarImagen.setToolTipText("Agrega una imagen del cliente");
        botonAgregarImagen.setEnabled(false);

        labelClave.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelClave.setForeground(new java.awt.Color(102, 102, 102));
        labelClave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelClave.setText("Clave:");

        campoTextoClave.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoTextoClave.setForeground(new java.awt.Color(102, 102, 102));
        campoTextoClave.setEnabled(false);
        campoTextoClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoClaveActionPerformed(evt);
            }
        });

        labelFechaAlta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelFechaAlta.setForeground(new java.awt.Color(102, 102, 102));
        labelFechaAlta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFechaAlta.setText("Fecha de Alta:");

        campoTextoFechaAlta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoTextoFechaAlta.setForeground(new java.awt.Color(102, 102, 102));
        campoTextoFechaAlta.setEnabled(false);

        labelNombres.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelNombres.setForeground(new java.awt.Color(102, 102, 102));
        labelNombres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombres.setText("Nombre(s):");

        campoTextoNombres.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoTextoNombres.setForeground(new java.awt.Color(102, 102, 102));
        campoTextoNombres.setEnabled(false);

        labelApellidoPaterno.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelApellidoPaterno.setForeground(new java.awt.Color(102, 102, 102));
        labelApellidoPaterno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelApellidoPaterno.setText("Apellido Paterno:");

        campoTextoApellidoPaterno.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoTextoApellidoPaterno.setForeground(new java.awt.Color(102, 102, 102));
        campoTextoApellidoPaterno.setEnabled(false);

        labelApellidoMaterno.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelApellidoMaterno.setForeground(new java.awt.Color(102, 102, 102));
        labelApellidoMaterno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelApellidoMaterno.setText("Apellido Materno:");

        campoTextoApellidoMaterno.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoTextoApellidoMaterno.setForeground(new java.awt.Color(102, 102, 102));
        campoTextoApellidoMaterno.setEnabled(false);

        labelGenero.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelGenero.setForeground(new java.awt.Color(102, 102, 102));
        labelGenero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGenero.setText("Género:");

        comboGenero.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        comboGenero.setForeground(new java.awt.Color(102, 102, 102));
        comboGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hombre", "Mujer" }));
        comboGenero.setEnabled(false);

        labelFechaNacimiento.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelFechaNacimiento.setForeground(new java.awt.Color(102, 102, 102));
        labelFechaNacimiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFechaNacimiento.setText("Fecha de Nacimiento:");

        campoTextoFechaNacimiento.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoTextoFechaNacimiento.setForeground(new java.awt.Color(102, 102, 102));
        campoTextoFechaNacimiento.setEnabled(false);

        campoTextoDomicilio.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoTextoDomicilio.setForeground(new java.awt.Color(102, 102, 102));
        campoTextoDomicilio.setEnabled(false);

        labelDomicilio.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelDomicilio.setForeground(new java.awt.Color(102, 102, 102));
        labelDomicilio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDomicilio.setText("Domicilio:");

        labelCelular.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelCelular.setForeground(new java.awt.Color(102, 102, 102));
        labelCelular.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCelular.setText("Celular:");

        campoTextoCelular.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoTextoCelular.setForeground(new java.awt.Color(102, 102, 102));
        campoTextoCelular.setEnabled(false);

        labelEmail.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(102, 102, 102));
        labelEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEmail.setText("Email:");

        campoTextoEmail.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoTextoEmail.setForeground(new java.awt.Color(102, 102, 102));
        campoTextoEmail.setEnabled(false);

        botonEditarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazUsuario/img/Editar.png"))); // NOI18N
        botonEditarCliente.setPreferredSize(new java.awt.Dimension(73, 73));
        botonEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarClienteActionPerformed(evt);
            }
        });

        botonGuardarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazUsuario/img/Guardar.png"))); // NOI18N
        botonGuardarCliente.setPreferredSize(new java.awt.Dimension(73, 73));
        botonGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarClienteActionPerformed(evt);
            }
        });

        botonEliminarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazUsuario/img/Eliminar.png"))); // NOI18N
        botonEliminarCliente.setPreferredSize(new java.awt.Dimension(73, 73));
        botonEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarClienteActionPerformed(evt);
            }
        });

        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazUsuario/img/Salir (1).png"))); // NOI18N
        botonSalir.setPreferredSize(new java.awt.Dimension(73, 73));
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelClientesLayout = new javax.swing.GroupLayout(panelClientes);
        panelClientes.setLayout(panelClientesLayout);
        panelClientesLayout.setHorizontalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonGuardarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelClientesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelClientesLayout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(botonAgregarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelClientesLayout.createSequentialGroup()
                                    .addComponent(labelClave)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(campoTextoClave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(labelFechaAlta)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(campoTextoFechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelClientesLayout.createSequentialGroup()
                                    .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelGenero)
                                        .addComponent(labelApellidoMaterno)
                                        .addComponent(labelApellidoPaterno)
                                        .addComponent(labelNombres)
                                        .addComponent(labelFechaNacimiento))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(campoTextoFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(campoTextoNombres)
                                        .addComponent(campoTextoApellidoPaterno)
                                        .addComponent(campoTextoApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(comboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                        .addGroup(panelClientesLayout.createSequentialGroup()
                            .addComponent(labelCelular)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(campoTextoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(labelEmail)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campoTextoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelClientesLayout.createSequentialGroup()
                            .addComponent(labelDomicilio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(campoTextoDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        panelClientesLayout.setVerticalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClientesLayout.createSequentialGroup()
                .addContainerGap(275, Short.MAX_VALUE)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonGuardarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelClientesLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelClientesLayout.createSequentialGroup()
                            .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelClave)
                                .addComponent(campoTextoClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelFechaAlta)
                                .addComponent(campoTextoFechaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2)
                            .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelNombres)
                                .addComponent(campoTextoNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelApellidoPaterno)
                                .addComponent(campoTextoApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelApellidoMaterno)
                                .addComponent(campoTextoApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(campoTextoFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(botonAgregarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelDomicilio)
                        .addComponent(campoTextoDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelCelular)
                        .addComponent(campoTextoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelEmail)
                        .addComponent(campoTextoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panelOdontograma.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Odontograma", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 10), new java.awt.Color(102, 102, 102))); // NOI18N

        panelDientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelPlacaSuperior.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelPlacaSuperior.setForeground(new java.awt.Color(102, 102, 102));
        labelPlacaSuperior.setText("Placa Superior");
        labelPlacaSuperior.setToolTipText("");

        diente18.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N

        diente15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diente15ActionPerformed(evt);
            }
        });

        diente14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diente14ActionPerformed(evt);
            }
        });

        diente24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diente24ActionPerformed(evt);
            }
        });

        diente25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diente25ActionPerformed(evt);
            }
        });

        diente28.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N

        diente38.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N

        diente35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diente35ActionPerformed(evt);
            }
        });

        diente34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diente34ActionPerformed(evt);
            }
        });

        diente44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diente44ActionPerformed(evt);
            }
        });

        diente45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diente45ActionPerformed(evt);
            }
        });

        diente48.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N

        labelPlacaInferior.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelPlacaInferior.setForeground(new java.awt.Color(102, 102, 102));
        labelPlacaInferior.setText("Placa Inferior");
        labelPlacaInferior.setToolTipText("");

        javax.swing.GroupLayout panelDientesLayout = new javax.swing.GroupLayout(panelDientes);
        panelDientes.setLayout(panelDientesLayout);
        panelDientesLayout.setHorizontalGroup(
            panelDientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDientesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(diente16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(labelPlacaSuperior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(diente26, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(panelDientesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(diente17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(diente27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(panelDientesLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(diente15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(diente25, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(panelDientesLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(diente14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diente13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diente12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diente11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(diente21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diente22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diente23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diente24, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(panelDientesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(diente18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(diente28, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelDientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(diente38, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(diente48, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelDientesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(diente37, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(diente47, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(panelDientesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(diente36, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(labelPlacaInferior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(diente46, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(panelDientesLayout.createSequentialGroup()
                .addGroup(panelDientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDientesLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(diente34, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(diente33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDientesLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(diente35, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelDientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDientesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(diente32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(diente31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(diente41, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(diente42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(diente43, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(diente44, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(panelDientesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(diente45, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        panelDientesLayout.setVerticalGroup(
            panelDientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDientesLayout.createSequentialGroup()
                .addGroup(panelDientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDientesLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(diente14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDientesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panelDientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(diente21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diente11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDientesLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelDientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(diente22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diente12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDientesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(diente24, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDientesLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panelDientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(diente23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diente13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(diente15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diente25, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDientesLayout.createSequentialGroup()
                        .addComponent(diente16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(diente17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDientesLayout.createSequentialGroup()
                        .addGroup(panelDientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(diente26, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPlacaSuperior))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(diente27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(diente18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diente28, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(diente38, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diente48, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(diente37, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diente47, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(diente36, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(diente46, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelPlacaInferior))
                .addGroup(panelDientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDientesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(diente35, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diente45, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDientesLayout.createSequentialGroup()
                                .addGap(0, 25, Short.MAX_VALUE)
                                .addGroup(panelDientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(diente43, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelDientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDientesLayout.createSequentialGroup()
                                            .addComponent(diente33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(35, 35, 35))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDientesLayout.createSequentialGroup()
                                            .addGroup(panelDientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(diente42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(diente32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(20, 20, 20)))))
                            .addGroup(panelDientesLayout.createSequentialGroup()
                                .addGroup(panelDientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(diente34, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(diente44, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDientesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelDientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(diente41, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diente31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout panelOdontogramaLayout = new javax.swing.GroupLayout(panelOdontograma);
        panelOdontograma.setLayout(panelOdontogramaLayout);
        panelOdontogramaLayout.setHorizontalGroup(
            panelOdontogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOdontogramaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOdontogramaLayout.setVerticalGroup(
            panelOdontogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOdontogramaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelConsultas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consultas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 10), new java.awt.Color(102, 102, 102))); // NOI18N

        tablaConsultas1.setAutoCreateRowSorter(true);
        tablaConsultas1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tablaConsultas1.setForeground(new java.awt.Color(102, 102, 102));
        tablaConsultas1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "12/12/1212", "Extraccion",  new Double(400.2)},
                { new Integer(2), "12/12/1212", "Limpieza",  new Double(200.5)},
                { new Integer(2), "12/12/1212", "Endodoncia",  new Double(400.5)},
                { new Integer(3), "12/12/1212", "Brakets",  new Double(600.0)},
                { new Integer(4), "12/12/1212", "Trabajo",  new Double(199.0)},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Pieza", "Fecha Consulta", "Trabajos Realizados", "Costo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaConsultas1.setGridColor(new java.awt.Color(153, 153, 153));
        tablaConsultas1.setRowHeight(20);
        tablaConsultas1.setSelectionBackground(new java.awt.Color(153, 153, 153));
        tablaConsultas.setViewportView(tablaConsultas1);

        campoTextoUltimaConsulta.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoTextoUltimaConsulta.setForeground(new java.awt.Color(102, 102, 102));
        campoTextoUltimaConsulta.setEnabled(false);

        labelUltimaConsulta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelUltimaConsulta.setForeground(new java.awt.Color(102, 102, 102));
        labelUltimaConsulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUltimaConsulta.setText("Última Consulta:");

        botonEliminarConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazUsuario/img/Eliminar.png"))); // NOI18N
        botonEliminarConsulta.setPreferredSize(new java.awt.Dimension(73, 73));
        botonEliminarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarConsultaActionPerformed(evt);
            }
        });

        campoTextoDeuda.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        campoTextoDeuda.setForeground(new java.awt.Color(102, 102, 102));
        campoTextoDeuda.setEnabled(false);

        labelDeuda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelDeuda.setForeground(new java.awt.Color(102, 102, 102));
        labelDeuda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDeuda.setText("Deuda:");

        botonInformacionConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazUsuario/img/Informacion.png"))); // NOI18N
        botonInformacionConsulta.setPreferredSize(new java.awt.Dimension(73, 73));
        botonInformacionConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInformacionConsultaActionPerformed(evt);
            }
        });

        botonAgregarConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazUsuario/img/Nuevo.png"))); // NOI18N
        botonAgregarConsulta.setPreferredSize(new java.awt.Dimension(73, 73));
        botonAgregarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarConsultaActionPerformed(evt);
            }
        });

        botonAgregarPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazUsuario/img/Pago.png"))); // NOI18N
        botonAgregarPago.setPreferredSize(new java.awt.Dimension(73, 73));
        botonAgregarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarPagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConsultasLayout = new javax.swing.GroupLayout(panelConsultas);
        panelConsultas.setLayout(panelConsultasLayout);
        panelConsultasLayout.setHorizontalGroup(
            panelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConsultasLayout.createSequentialGroup()
                        .addComponent(labelUltimaConsulta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoTextoUltimaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelDeuda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoTextoDeuda, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(botonAgregarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonAgregarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonInformacionConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEliminarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tablaConsultas))
                .addContainerGap())
        );
        panelConsultasLayout.setVerticalGroup(
            panelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultasLayout.createSequentialGroup()
                .addGroup(panelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(botonEliminarConsulta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                        .addComponent(botonAgregarConsulta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(botonInformacionConsulta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(botonAgregarPago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(panelConsultasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelUltimaConsulta)
                            .addComponent(campoTextoUltimaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDeuda)
                            .addComponent(campoTextoDeuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tablaConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelOdontograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelOdontograma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarClienteActionPerformed
        campoTextoNombres.setEnabled(false);
        campoTextoApellidoPaterno.setEnabled(false);
        campoTextoApellidoMaterno.setEnabled(false);
        comboGenero.setEnabled(false);
        campoTextoFechaNacimiento.setEnabled(false);
        campoTextoDomicilio.setEnabled(false);
        campoTextoCelular.setEnabled(false);
        campoTextoEmail.setEnabled(false);
        botonAgregarImagen.setEnabled(false);
    }//GEN-LAST:event_botonGuardarClienteActionPerformed

    private void botonEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarClienteActionPerformed
        AdministrarClientes abrirClientes = new AdministrarClientes();
        abrirClientes.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonEliminarClienteActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        AdministrarClientes abrirClientes = new AdministrarClientes();
        abrirClientes.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonEliminarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarConsultaActionPerformed

    private void botonInformacionConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInformacionConsultaActionPerformed
        InformacionConsulta abrirConsulta = new InformacionConsulta();
        abrirConsulta.setVisible(true);
    }//GEN-LAST:event_botonInformacionConsultaActionPerformed

    private void botonAgregarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarConsultaActionPerformed
        AgregarConsulta nuevaConsulta = new AgregarConsulta();
        nuevaConsulta.setVisible(true);
    }//GEN-LAST:event_botonAgregarConsultaActionPerformed

    private void botonAgregarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarPagoActionPerformed
        AgregarPago pagar = new AgregarPago();
        pagar.setVisible(true);
    }//GEN-LAST:event_botonAgregarPagoActionPerformed

    private void diente15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diente15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diente15ActionPerformed

    private void diente14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diente14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diente14ActionPerformed

    private void diente24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diente24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diente24ActionPerformed

    private void diente25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diente25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diente25ActionPerformed

    private void diente35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diente35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diente35ActionPerformed

    private void diente34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diente34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diente34ActionPerformed

    private void diente45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diente45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diente45ActionPerformed

    private void diente44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diente44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diente44ActionPerformed

    private void botonEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarClienteActionPerformed
        campoTextoNombres.setEnabled(true);
        campoTextoApellidoPaterno.setEnabled(true);
        campoTextoApellidoMaterno.setEnabled(true);
        comboGenero.setEnabled(true);
        campoTextoFechaNacimiento.setEnabled(true);
        campoTextoDomicilio.setEnabled(true);
        campoTextoCelular.setEnabled(true);
        campoTextoEmail.setEnabled(true);
        botonAgregarImagen.setEnabled(true);
    }//GEN-LAST:event_botonEditarClienteActionPerformed

    private void campoTextoClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoClaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistorialCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistorialCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistorialCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistorialCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistorialCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarConsulta;
    private javax.swing.JButton botonAgregarImagen;
    private javax.swing.JButton botonAgregarPago;
    private javax.swing.JButton botonEditarCliente;
    private javax.swing.JButton botonEliminarCliente;
    private javax.swing.JButton botonEliminarConsulta;
    private javax.swing.JButton botonGuardarCliente;
    private javax.swing.JButton botonInformacionConsulta;
    private javax.swing.JButton botonSalir;
    private javax.swing.JTextField campoTextoApellidoMaterno;
    private javax.swing.JTextField campoTextoApellidoPaterno;
    private javax.swing.JTextField campoTextoCelular;
    private javax.swing.JTextField campoTextoClave;
    private javax.swing.JTextField campoTextoDeuda;
    private javax.swing.JTextField campoTextoDomicilio;
    private javax.swing.JTextField campoTextoEmail;
    private javax.swing.JTextField campoTextoFechaAlta;
    private javax.swing.JTextField campoTextoFechaNacimiento;
    private javax.swing.JTextField campoTextoNombres;
    private javax.swing.JTextField campoTextoUltimaConsulta;
    private javax.swing.JComboBox comboGenero;
    private javax.swing.JButton diente11;
    private javax.swing.JButton diente12;
    private javax.swing.JButton diente13;
    private javax.swing.JButton diente14;
    private javax.swing.JButton diente15;
    private javax.swing.JButton diente16;
    private javax.swing.JButton diente17;
    private javax.swing.JButton diente18;
    private javax.swing.JButton diente21;
    private javax.swing.JButton diente22;
    private javax.swing.JButton diente23;
    private javax.swing.JButton diente24;
    private javax.swing.JButton diente25;
    private javax.swing.JButton diente26;
    private javax.swing.JButton diente27;
    private javax.swing.JButton diente28;
    private javax.swing.JButton diente31;
    private javax.swing.JButton diente32;
    private javax.swing.JButton diente33;
    private javax.swing.JButton diente34;
    private javax.swing.JButton diente35;
    private javax.swing.JButton diente36;
    private javax.swing.JButton diente37;
    private javax.swing.JButton diente38;
    private javax.swing.JButton diente41;
    private javax.swing.JButton diente42;
    private javax.swing.JButton diente43;
    private javax.swing.JButton diente44;
    private javax.swing.JButton diente45;
    private javax.swing.JButton diente46;
    private javax.swing.JButton diente47;
    private javax.swing.JButton diente48;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelApellidoMaterno;
    private javax.swing.JLabel labelApellidoPaterno;
    private javax.swing.JLabel labelCelular;
    private javax.swing.JLabel labelClave;
    private javax.swing.JLabel labelDeuda;
    private javax.swing.JLabel labelDomicilio;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelFechaAlta;
    private javax.swing.JLabel labelFechaNacimiento;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JLabel labelNombres;
    private javax.swing.JLabel labelPlacaInferior;
    private javax.swing.JLabel labelPlacaSuperior;
    private javax.swing.JLabel labelUltimaConsulta;
    private javax.swing.JPanel panelClientes;
    private javax.swing.JPanel panelConsultas;
    private javax.swing.JPanel panelDientes;
    private javax.swing.JPanel panelOdontograma;
    private javax.swing.JScrollPane tablaConsultas;
    private javax.swing.JTable tablaConsultas1;
    // End of variables declaration//GEN-END:variables
}
